hello_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from my_app.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^my_app/', include('my_app.urls', namespace='my')),
]

my_app/urls.py
from django.conf.urls import url
from my_app.views import *

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^index/(\d*)$', index, name='index'),
    url(r'^post/$', save_post, name='post'),
    url(r'^post/(\d)', detail, name='detail'),
    url(r'^update/(\d+)$', update_post, name='update'),
    url(r'^delete/(\d+)$', delete_post, name='delete'),
    url(r'^gen_post/', gen_post, name='gen_post'),
    url(r'^gen_score/', gen_score, name='gen_score'),
    url(r'^form', get_form, name='form'),
    url(r'^template_demo', template_demo, name='template_demo'),
    url(r'^register/', register, name='register'),
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
]

my_app/models.py
from django.db import models

# Create your models here.


class NormalManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(excerpt__exact="normal")


class SecretManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(excerpt__exact="secret")


class Post(models.Model):
    title = models.CharField(max_length=128)
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True, auto_created=True, null=True)
    modified_time = models.DateTimeField(auto_now_add=True, auto_created=True, null=True)
    excerpt = models.CharField(max_length=400, default="None")
    category = models.ForeignKey("Category")
    tags = models.ManyToManyField("Tag")
    # noraml_objects = NormalManager()
    # secret_objects = SecretManager()

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



class Score(models.Model):
    class Meta:
        verbose_name = "分数表"
        verbose_name_plural = "分数表"
    name = models.CharField(max_length=10, verbose_name="姓名")
    math = models.PositiveIntegerField(verbose_name="数学")
    chinese = models.PositiveIntegerField(default=88, verbose_name="语文")

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveIntegerField(default=20)
    grade = models.ForeignKey("Grade")
    gender = models.BooleanField(default=False)


class GradeManager(models.Manager):
    def search_title_by_kw(self, kw):
        return self.filter(name__contains=kw)

    def get_queryset(self):
        return super().get_queryset().filter(is_delete=0)


class Grade(models.Model):
    name = models.CharField(max_length=50)
    num = models.PositiveIntegerField(default=10)
    created_time = models.DateTimeField(auto_now_add=True)
    is_delete = models.BooleanField(default=0)
    grade_manager = GradeManager()


class UserInfo(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField()
    passwd = models.CharField(max_length=400)

    def __str__(self):
        return self.username


class People(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class IDCard(models.Model):
    num = models.CharField(max_length=18)
    people = models.OneToOneField(People, on_delete=models.PROTECT)

    def __str__(self):
        return self.num

my_app/views.py
import random

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.db.models import Max, Min, Count, Avg, Sum, F, Q
from django.urls import reverse
from django.core.paginator import Paginator

from my_app.models import Post, Score, UserInfo, Category


# Create your views here.

def home(request):
    name = request.session.get('user')
    # print("request encoding" + str(request.encoding))
    # print("request post" + str(request.POST))
    # print("request get" + str(request.GET))
    # print("request method" + str(request.method))
    # print("request path" + str(request.path))
    # print("request cookies" + str(request.COOKIES))
    # print("request session" + str(request.session))
    # print(request.is_ajax())
    # print(request.get_host())

    # first_boj = Post.objects.first()
    # last_object = Post.objects.last()
    # count_obj = Post.objects.count()
    # exist_bool = Post.objects.exists()
    # print(first_boj)
    # print(last_object)
    # print(count_obj)
    # print(exist_bool)
    # student = Score.objects.filter(~Q(math__gte=90)).values("name", "math", "chinese")
    # print(student)
    # a = 10/0
    request.session.flush()
    return HttpResponse("欢迎您 %s!" %name)


def index(request, num=1):
    if not num:
        num = 1
    post_list = Post.objects.all().values("id", "title")
    paginator = Paginator(post_list, 10)
    page = paginator.page(num)
    page_list = page.object_list
    page_range = paginator.page_range
    print(page_list)
    return render(request, 'my_app/index.html', context={"page_list": page_list, "page_range": page_range, 'page':page})


def save_post(request):
    if request.method == "GET":
        return render(request, 'my_app/post_form.html')
    elif request.method == "POST":
        title = request.POST.get("title")
        body = request.POST.get("body")
        Post.objects.create(title=title, body=body)
        return HttpResponse("文章：%s保存成功" % title)


def detail(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'my_app/detail.html', context={"post": post})


def update_post(request, id):
    if request.method == "GET":
        post = get_object_or_404(Post, id=id)
        return render(request, "my_app/update.html", context={"post": post})
    elif request.method == "POST":
        new_title = request.POST.get('new_title')
        new_body = request.POST.get('new_body')
        if not id:
            return HttpResponse("请输入文章ID")
        if not new_title and not new_body:
            return HttpResponse("标题和内容不能都为空")
        post = Post.objects.get(id=id)
        if new_title:
            post.title = new_title
        if new_body:
            post.body = new_body
        post.save()
        return HttpResponse("修改成功！")


def delete_post(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return HttpResponse("删除成功！")


def gen_post(request):
    category = Category.objects.first()
    for i in range(100):
        title = "post" + str(random.randrange(100))
        body = "body of " + title
        Post.objects.create(title=title, body=body, category=category)
    return HttpResponse("生成了100篇文章！")


def gen_score(request):
    for i in range(100):
        name = "Student" + str(random.randrange(100))
        math = random.randrange(50, 100)
        chinese = random.randrange(40, 90)
        Score.objects.create(name=name, math=math, chinese=chinese)
    return HttpResponse("生成了100个学生的成绩！")


def get_form(request):
    if request.method == "GET":
        # a = 10 / 0
        resp = render(request, 'my_app/form.html')
        print(resp.content)
        print(resp.charset)
        print(resp)
        resp.write("Hello Word")
        return resp
        # return redirect(reverse('my:detail', args=(5, )))
    elif request.method == "POST":
        name = request.POST.get('name')
        passwd = request.POST.get('passwd')
        request.session['user'] = name
        request.session.set_expiry(60)
        print(name)
        print(passwd)
        resp = HttpResponse(("注册成功！"))
        # resp.set_cookie('name', name, max_age=30)
        return resp


def template_demo(request):
    people_dict = {"name": 'Even', "age": "10"}
    data_list = [1, 2, 4, 5, 6]
    return render(request, 'my_app/my_page.html', context={"people_info": people_dict, 'data_list': data_list})


def register(request):
    if request.method == "POST":
        username = request.POST.get("username")
        passwd = request.POST.get("passwd")
        email = request.POST.get('email')
        confirm_passwd = request.POST.get("passwd_confirm")
        print(username, email, passwd, confirm_passwd)
        if not username and not email and not passwd and not confirm_passwd:
            return HttpResponse("请检查是否漏填")
        if passwd == confirm_passwd:
            from my_app.tools import gen_secret
            passwd = gen_secret(passwd)
            request.session['username'] = username
            UserInfo.objects.create(username=username, email=email, passwd=passwd)
            return render(request, 'my_app/register.html')
        return HttpResponse("密码不一致，请重新注册！")
    return render(request, "my_app/register.html")


def login(request):
    username = request.POST.get('username')
    passwd = request.POST.get('passwd')
    session_username = request.session.get('username')
    print(username, passwd, session_username)
    if username == session_username:
        from my_app.tools import gen_secret
        passwd = gen_secret(passwd)
        db_passwd = UserInfo.objects.filter(username=username)[0].passwd
        print(db_passwd)
        if passwd == db_passwd:
            return render(request, 'my_app/user_center.html', context={'username': username})
        return HttpResponse("账号或密码有误，请重新输入")
    return HttpResponse("账号或密码有误，请重新输入！")


def logout(request):
    request.session.flush()
    username = request.session.get("username")
    print(username)
    return render(request, 'my_app/user_center.html', context={'username': username})

templates/my_app/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>博客正文</title>
</head>
<body>
    <h1>{{ post.title }}</h1>

    <div>
        <p>{{ post.body }}</p>
    </div>
    <buton><a href="{% url 'my:update' post.id %}">修改博文</a></buton>&nbsp;&nbsp;<button><a href="{% url 'my:delete' post.id %}">删除博文</a></button>
</body>
</html>

templates/my_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表单填写</title>
</head>
<body>
<form action="{% url 'my:form' %}" method="post">
    {% csrf_token %}
    姓名：<input type="text" name="name" id=""> <br>
    密码：<input type="password" name="passwd" id=""> <br>
    <input type="submit" value="注册">
</form>
</body>
</html>

templates/my_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>博客首页</title>
</head>
<body>
    <h1>博客列表</h1>
    <ul>
        {% for post in page_list %}
            <li style="color: gray"><a href="{% url 'my:detail' post.id %}">{{ post.title }}</a></li>
    {% endfor %}
    </ul>

<nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
        {% if page.has_previous %}
            <a href="{% url 'my:index' page.previous_page_number %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        {% else %}
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        {% endif %} 

    </li>
      {% for num in page_range %}
          {% ifequal page.number num %}
              <li class="active"><a href="{% url 'my:index' num %}">{{num}} <span class="sr-only">(current)</span></a></li>
          {% else %}
              <li class="disabled"><a href="{% url 'my:index' num %}">{{num}} <span class="sr-only">(current)</span></a></li>
          {% endifequal %}
      {% endfor %}
    <li>
        {% if page.has_next %}
            <a href="{% url 'my:index' page.next_page_number %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        {% else %}
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        {% endif %}

    </li>
  </ul>
</nav>
</body>
</html>

templates/my_app/my_page.html
{% extends 'base.html' %}

{% block title %}
    主页
{% endblock %}

{% block main %}
    <p style="color: red">这是填充的内容</p>
{% endblock %}

templates/my_app/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编写博客</title>
</head>
<body>

<form action="/post/", method="post">
    {% csrf_token %}
    文章标题：<input type="text" name="title" id=""> <br>
    正文：<input type="text" name="body" id=""> <br>
    <input type="submit" value="保存文章">

</form>

</body>
</html>

templates/my_app/register.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="zh" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/animate-custom.css' %}" />
    </head>
    <body>
        <div class="container">
            <header>
                <h1>欢迎登陆我的 <span>博客</span></h1>
				<nav class="codrops-demos">
					<span>点击 <strong>"加入我们"</strong> 即可注册</span>
					<a href="register.html" class="current-demo">回到首页</a>
				</nav>
            </header>
            <section>				
                <div id="container_demo" >
                    <a class="hiddenanchor" id="toregister"></a>
                    <a class="hiddenanchor" id="tologin"></a>
                    <div id="wrapper">
                        <div id="login" class="animate form">
                            <form  action="/my_app/login/" method="post" autocomplete="on">
                                {% csrf_token %}
                                <h1>登录</h1>
                                <p> 
                                    <label for="username" class="uname" data-icon="u" > 用户名 </label>
                                    <input id="username" name="username" required="required" type="text" placeholder="请输入用户名"/>
                                </p>
                                <p> 
                                    <label for="password" class="youpasswd" data-icon="p"> 密码 </label>
                                    <input id="password" name="passwd" required="required" type="password" placeholder="请输入密码" /> 
                                </p>
                                <p class="keeplogin"> 
									<input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" /> 
									<label for="loginkeeping">记住密码</label>
								</p>
                                <p class="login button"> 
                                    <input type="submit" value="登录" />
								</p>
                                <p class="change_link">
									没有账号 ?
									<a href="#toregister" class="to_register">加入我们</a>
								</p>
                            </form>
                        </div>

                        <div id="register" class="animate form">
                            <form  action="/my_app/register/" method="post" autocomplete="on">
                                {% csrf_token %}
                                <h1> 注册 </h1> 
                                <p> 
                                    <label for="usernamesignup" class="uname" data-icon="u">用户名</label>
                                    <input id="username" name="username" required="required" type="text" placeholder="取个帅气的名字吧" />
                                </p>
                                <p> 
                                    <label for="emailsignup" class="youmail" data-icon="e" > 邮箱</label>
                                    <input id="emailsignup" name="email" required="required" type="email" placeholder="请输入你的邮箱"/> 
                                </p>
                                <p> 
                                    <label for="passwordsignup" class="youpasswd" data-icon="p">密码 </label>
                                    <input id="passwordsignup" name="passwd" required="required" type="password" placeholder="请确认四周无人，捂紧键盘，偷偷输入密码"/>
                                </p>
                                <p> 
                                    <label for="passwordsignup_confirm" class="youpasswd" data-icon="p">确认密码 </label>
                                    <input id="passwordsignup_confirm" name="passwd_confirm" required="required" type="password" placeholder="请确认密码"/>
                                </p>
                                <p class="signin button"> 
									<input type="submit" value="注册"/> 
								</p>
                                <p class="change_link">  
									已有账号 ?
									<a href="#tologin" class="to_register"> 登录 </a>
								</p>
                            </form>
                        </div>
						
                    </div>
                </div>  
            </section>
        </div>
    </body>
</html>

templates/my_app/template_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ people_info.name }}

    {% for data in data_list %}
        {{ forloop.counter }}:{{ data }}
        {% ifequal forloop.counter 4 %}
            Hi
        {% endifequal %}
    {% endfor %}
    {{ "Hello"|truncatechars:4 }}

    {% autoescape on %}
        &nbsp;
    {% endautoescape %}

    {# 这是单行注释 #}
    {% comment %}
    多行注释
    ads
    f
    adsf
    adsf
    {% endcomment %}

    <!-- HTML的注释 -->
</body>
</html>

templates/my_app/update.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>修改文章</title>
</head>
<body>
<form action="{% url 'my:update' post.id %}" method="post">
    {% csrf_token %}
    修改后的文章标题： <input type="text" name="new_title" id=""><br>
    修改后的文章内容：<input type="text" name="new_body" id="">
    <input type="submit" value="提交修改">
</form>

</body>
</html>

templates/my_app/user_center.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    欢迎您，
    {% if username %}
        {{ username }},
    {% else %}
        游客。<br>
        <a href="/my_app/register/">点我注册！</a>
    {% endif %}
    <a href="/my_app/logout"><button>注销</button></a>
</body>
</html>